### ISSUE TITLE
Next card should be destroyable

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/next-card#38]
Rule 4 ;-)
http://origami.ft.com/docs/syntax/js/#encapsulation-rules

**Comment by keirog** [comment]
@matthew-andrews Is there a use-case for this? It doesn't seem like Origami components themselves even adhere to that rule (eg. https://github.com/Financial-Times/o-date)

**Comment by keirog** [comment]
fwiw though, I agree with the rule…

**Comment by matthew-andrews** [comment]
yup.  @i-like-robots and i want to build functional for streaming content into streams, and will be replacing part of the dom so to prevent memory leeks we would like to be confident that anything that was there is no more.

![483-memory-leek](https://cloud.githubusercontent.com/assets/825088/8078278/72e07614-0f54-11e5-9141-29dae569fe6c.png)

for now we can just put our heads in the sand and not bother.

**Comment by keirog** [comment]
not sure if sarcasm?
if so, all next-card's JS does is call init on two other, non-destroyable components…

**Comment by matthew-andrews** [comment]
not sarcasm :speak_no_evil: !  i didn't realise those other components also didn't have `destroy` methods.  i thought o-date updated live as time went on (perhaps again false assumption) so i would have thought there would be the potential for leaky logic but maybe not, maybe it's fine
